In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv('../data/student_performance.csv')


print("number of students: ", len(df))
print("number of features: ", len(df.columns))
print("\nAverage Overall Score: ",df['Overall Score'].mean())
print("missing values: ", df.isnull().sum().sum())
print("datatypes: ", df.dtypes)

number of students:  161
number of features:  11

Average Overall Score:  74.48227848101266
missing values:  60
datatypes:  Student ID              str
Student Name            str
Gender                  str
Class                   str
Subject                 str
Study Hours         float64
Attendance %        float64
Assignment Score    float64
Midterm Score       float64
Final Exam Score    float64
Overall Score       float64
dtype: object

In [2]:
df.head()
df.info()
df.describe()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student ID        158 non-null    str
 1   Student Name      158 non-null    str
 2   Gender            155 non-null    str
 3   Class             154 non-null    str
 4   Subject           158 non-null    str
 5   Study Hours       158 non-null    float64
 6   Attendance %      152 non-null    float64
 7   Assignment Score  153 non-null    float64
 8   Midterm Score     154 non-null    float64
 9   Final Exam Score  153 non-null    float64
 10  Overall Score     158 non-null    float64
dtypes: float64(6), str(5)
memory usage: 14.0 KB

Index(['Student ID', 'Student Name', 'Gender', 'Class', 'Subject',
       'Study Hours', 'Attendance %', 'Assignment Score', 'Midterm Score',
       'Final Exam Score', 'Overall Score'],
      dtype='str')

In [3]:
print("Duplicate rows: ", df.duplicated().sum())

Duplicate rows:  7

In [4]:
df.isnull().sum()

Student ID          3
Student Name        3
Gender              6
Class               7
Subject             3
Study Hours         3
Attendance %        9
Assignment Score    8
Midterm Score       7
Final Exam Score    8
Overall Score       3
dtype: int64

In [5]:
score_columns = [
    "Assignment Score",
    "Midterm Score",
    "Final Exam Score",
    "Overall Score"
]
df[score_columns].dtypes

Assignment Score    float64
Midterm Score       float64
Final Exam Score    float64
Overall Score       float64
dtype: object

In [6]:
df.columns
df.head()

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
0,STU092,Student 092,Female,10th,English,3.9,90.9,60.0,55.8,77.0,69.5
1,STU047,Student 047,Male,9th,Computer Science,5.1,90.1,65.7,99.2,85.6,92.3
2,STU003,STUDENT 003,Male,9th,English,3.9,84.5,66.4,100.0,100.0,96.1
3,STU104,Student 104,Female,10TH,Computer Science,2.8,73.3,NaN,83.2,83.2,69.7
4,STU099,Student 099,Male,12th,Physics,4.5,67.8,53.5,81.3,83.4,71.2

In [ ]:
df.isnull().sum()

Student ID          3
Student Name        3
Gender              6
Class               7
Subject             3
Study Hours         3
Attendance %        9
Assignment Score    8
Midterm Score       7
Final Exam Score    8
Overall Score       3
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
3,STU104,Student 104,Female,10TH,Computer Science,2.8,73.3,NaN,83.2,83.2,69.7
10,STU015,Student 015,NaN,10th,English,4.6,89.0,51.4,70.7,71.4,72.5
29,STU066,Student 066,Male,12th,English,6.4,NaN,91.3,97.7,71.9,78.7
35,STU090,Student 090,Male,11th,MATHEMATICS,3.8,84.2,75.6,NaN,73.4,59.9
53,STU093,Student 093,Female,10th,Chemistry,2.2,NaN,45.2,76.6,52.6,64.1
60,STU142,Student 142,NaN,9th,Physics,1.0,67.4,40.9,NaN,32.5,36.8
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,STU070,Student 070,Male,9th,Physics,4.4,89.2,64.1,96.0,NaN,72.9
78,STU135,Student 135,Female,NaN,Mathematics,3.5,88.2,89.2,75.4,55.5,72.2
84,STU043,Student 043,Male,9th,Mathematics,1.9,NaN,NaN,79.8,36.4,50.7
89,STU128,Student 128,Male,9th,Physics,2.8,67.3,68.0,63.8,NaN,62.5
97,STU126,Student 126,Female,NaN,Mathematics,1.7,63.0,52.3,59.4,42.6,55.0
112,STU062,Student 062,Female,9th,Mathematics,2.5,73.0,NaN,60.5,70.1,74.1
115,STU002,STUDENT 002,Female,10th,Computer science,5.0,NaN,100.0,100.0,86.6,95.2
116,STU120,Student 120,Female,12th,Chemistry,2.5,92.5,61.1,NaN,70.1,71.5
117,STU132,Student 132,Male,9th,English,3.5,93.4,NaN,73.3,78.2,73.3
120,STU089,Student 089,Female,NaN,Computer Science,4.7,87.3,82.0,85.2,78.9,81.3
121,STU139,Student 139,Female,10th,Physics,3.9,71.2,97.2,82.3,NaN,66.6
133,STU002,Student 002,Female,10th,Computer science,5.0,NaN,100.0,100.0,86.6,95.2
136,STU023,Student 023,Female,9th,Mathematics,4.1,59.6,71.8,82.3,NaN,75.6
138,STU100,Student 100,Male,10th,English,3.8,NaN,64.2,72.2,59.3,65.6
143,STU063,Student 063,Male,9th,English,2.9,81.6,NaN,87.0,62.0,79.8
145,STU048,Student 048,NaN,11th,Mathematics,3.5,77.7,85.0,80.6,62.1,69.7
146,STU080,Student 080,Female,12th,English,2.3,73.2,92.2,NaN,48.4,66.7
153,STU060,Student 060,Female,NaN,Physics,1.0,83.0,54.3,41.0,NaN,47.6
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[df.isnull().all(axis=1)]

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().all(axis=1).sum()

np.int64(3)

In [ ]:
df = df.dropna(how="all")

In [ ]:
df.shape

(158, 11)

In [ ]:
df.isnull().sum()

Student ID          0
Student Name        0
Gender              3
Class               4
Subject             0
Study Hours         0
Attendance %        6
Assignment Score    5
Midterm Score       4
Final Exam Score    5
Overall Score       0
dtype: int64

In [ ]:
df = df.dropna(how="all")

In [ ]:
df.isnull().sum()

Student ID          0
Student Name        0
Gender              3
Class               4
Subject             0
Study Hours         0
Attendance %        6
Assignment Score    5
Midterm Score       4
Final Exam Score    5
Overall Score       0
dtype: int64

In [ ]:
missing_rows = df[df.isnull().any(axis=1)]

missing_rows

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
3,STU104,Student 104,Female,10TH,Computer Science,2.8,73.3,NaN,83.2,83.2,69.7
10,STU015,Student 015,NaN,10th,English,4.6,89.0,51.4,70.7,71.4,72.5
29,STU066,Student 066,Male,12th,English,6.4,NaN,91.3,97.7,71.9,78.7
35,STU090,Student 090,Male,11th,MATHEMATICS,3.8,84.2,75.6,NaN,73.4,59.9
53,STU093,Student 093,Female,10th,Chemistry,2.2,NaN,45.2,76.6,52.6,64.1
60,STU142,Student 142,NaN,9th,Physics,1.0,67.4,40.9,NaN,32.5,36.8
76,STU070,Student 070,Male,9th,Physics,4.4,89.2,64.1,96.0,NaN,72.9
78,STU135,Student 135,Female,NaN,Mathematics,3.5,88.2,89.2,75.4,55.5,72.2
84,STU043,Student 043,Male,9th,Mathematics,1.9,NaN,NaN,79.8,36.4,50.7
89,STU128,Student 128,Male,9th,Physics,2.8,67.3,68.0,63.8,NaN,62.5
97,STU126,Student 126,Female,NaN,Mathematics,1.7,63.0,52.3,59.4,42.6,55.0
112,STU062,Student 062,Female,9th,Mathematics,2.5,73.0,NaN,60.5,70.1,74.1
115,STU002,STUDENT 002,Female,10th,Computer science,5.0,NaN,100.0,100.0,86.6,95.2
116,STU120,Student 120,Female,12th,Chemistry,2.5,92.5,61.1,NaN,70.1,71.5
117,STU132,Student 132,Male,9th,English,3.5,93.4,NaN,73.3,78.2,73.3
120,STU089,Student 089,Female,NaN,Computer Science,4.7,87.3,82.0,85.2,78.9,81.3
121,STU139,Student 139,Female,10th,Physics,3.9,71.2,97.2,82.3,NaN,66.6
133,STU002,Student 002,Female,10th,Computer science,5.0,NaN,100.0,100.0,86.6,95.2
136,STU023,Student 023,Female,9th,Mathematics,4.1,59.6,71.8,82.3,NaN,75.6
138,STU100,Student 100,Male,10th,English,3.8,NaN,64.2,72.2,59.3,65.6
143,STU063,Student 063,Male,9th,English,2.9,81.6,NaN,87.0,62.0,79.8
145,STU048,Student 048,NaN,11th,Mathematics,3.5,77.7,85.0,80.6,62.1,69.7
146,STU080,Student 080,Female,12th,English,2.3,73.2,92.2,NaN,48.4,66.7
153,STU060,Student 060,Female,NaN,Physics,1.0,83.0,54.3,41.0,NaN,47.6

In [ ]:
missing_rows.isnull().sum(axis=1)

3      1
10     1
29     1
35     1
53     1
60     2
76     1
78     1
84     2
89     1
97     1
112    1
115    1
116    1
117    1
120    1
121    1
133    1
136    1
138    1
143    1
145    1
146    1
153    2
dtype: int64

In [ ]:
missing_rows

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
3,STU104,Student 104,Female,10TH,Computer Science,2.8,73.3,NaN,83.2,83.2,69.7
10,STU015,Student 015,NaN,10th,English,4.6,89.0,51.4,70.7,71.4,72.5
29,STU066,Student 066,Male,12th,English,6.4,NaN,91.3,97.7,71.9,78.7
35,STU090,Student 090,Male,11th,MATHEMATICS,3.8,84.2,75.6,NaN,73.4,59.9
53,STU093,Student 093,Female,10th,Chemistry,2.2,NaN,45.2,76.6,52.6,64.1
60,STU142,Student 142,NaN,9th,Physics,1.0,67.4,40.9,NaN,32.5,36.8
76,STU070,Student 070,Male,9th,Physics,4.4,89.2,64.1,96.0,NaN,72.9
78,STU135,Student 135,Female,NaN,Mathematics,3.5,88.2,89.2,75.4,55.5,72.2
84,STU043,Student 043,Male,9th,Mathematics,1.9,NaN,NaN,79.8,36.4,50.7
89,STU128,Student 128,Male,9th,Physics,2.8,67.3,68.0,63.8,NaN,62.5
97,STU126,Student 126,Female,NaN,Mathematics,1.7,63.0,52.3,59.4,42.6,55.0
112,STU062,Student 062,Female,9th,Mathematics,2.5,73.0,NaN,60.5,70.1,74.1
115,STU002,STUDENT 002,Female,10th,Computer science,5.0,NaN,100.0,100.0,86.6,95.2
116,STU120,Student 120,Female,12th,Chemistry,2.5,92.5,61.1,NaN,70.1,71.5
117,STU132,Student 132,Male,9th,English,3.5,93.4,NaN,73.3,78.2,73.3
120,STU089,Student 089,Female,NaN,Computer Science,4.7,87.3,82.0,85.2,78.9,81.3
121,STU139,Student 139,Female,10th,Physics,3.9,71.2,97.2,82.3,NaN,66.6
133,STU002,Student 002,Female,10th,Computer science,5.0,NaN,100.0,100.0,86.6,95.2
136,STU023,Student 023,Female,9th,Mathematics,4.1,59.6,71.8,82.3,NaN,75.6
138,STU100,Student 100,Male,10th,English,3.8,NaN,64.2,72.2,59.3,65.6
143,STU063,Student 063,Male,9th,English,2.9,81.6,NaN,87.0,62.0,79.8
145,STU048,Student 048,NaN,11th,Mathematics,3.5,77.7,85.0,80.6,62.1,69.7
146,STU080,Student 080,Female,12th,English,2.3,73.2,92.2,NaN,48.4,66.7
153,STU060,Student 060,Female,NaN,Physics,1.0,83.0,54.3,41.0,NaN,47.6

In [ ]:
# Make a copy of the cleaned dataset
clean_df = df.copy()

# Fill missing categorical values
clean_df["Gender"] = clean_df["Gender"].fillna("Unknown")
clean_df["Class"] = clean_df["Class"].fillna("Unknown")

# Fill missing numerical values with the median
numeric_columns = [
    "Attendance %",
    "Assignment Score",
    "Midterm Score",
    "Final Exam Score"
]

for column in numeric_columns:
    clean_df[column] = clean_df[column].fillna(
        clean_df[column].median()
    )

clean_df.head()

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
0,STU092,Student 092,Female,10th,English,3.9,90.9,60.0,55.8,77.0,69.5
1,STU047,Student 047,Male,9th,Computer Science,5.1,90.1,65.7,99.2,85.6,92.3
2,STU003,STUDENT 003,Male,9th,English,3.9,84.5,66.4,100.0,100.0,96.1
3,STU104,Student 104,Female,10TH,Computer Science,2.8,73.3,70.4,83.2,83.2,69.7
4,STU099,Student 099,Male,12th,Physics,4.5,67.8,53.5,81.3,83.4,71.2

In [ ]:
clean_df.isnull().sum()

Student ID          0
Student Name        0
Gender              0
Class               0
Subject             0
Study Hours         0
Attendance %        0
Assignment Score    0
Midterm Score       0
Final Exam Score    0
Overall Score       0
dtype: int64

In [ ]:
clean_df.shape
clean_df["Student ID"].nunique()

150

In [ ]:
clean_df["Final Exam Score"].mean()

np.float64(71.50886075949369)

In [ ]:
clean_df["Overall Score"].mean()

np.float64(74.48227848101266)

In [ ]:
clean_df["Overall Score"].max()

np.float64(100.0)

In [ ]:
clean_df["Overall Score"].min()

np.float64(36.8)

In [ ]:
clean_df.sort_values(
    by="Overall Score",
    ascending=False
).head(15)

,Student ID,Student Name,Gender,Class,Subject,Study Hours,Attendance %,Assignment Score,Midterm Score,Final Exam Score,Overall Score
124,STU013,Student 013,Male,12th,Physics,7.5,100.00,97.1,100.0,100.0,100.0
142,STU144,Student 144,Male,12th,Physics,5.4,95.90,83.5,100.0,100.0,100.0
2,STU003,STUDENT 003,Male,9th,English,3.9,84.50,66.4,100.0,100.0,96.1
43,STU003,Student 003,Male,9th,English,3.9,84.50,66.4,100.0,100.0,96.1
52,STU027,Student 027,Female,9th,physics,5.2,100.00,96.6,100.0,94.2,96.0
20,STU044,Student 044,Female,10th,math,5.2,89.10,85.9,100.0,97.1,95.7
141,STU018,Student 018,Female,9th,English,5.5,97.00,81.8,100.0,93.7,95.7
6,STU050,Student 050,Male,11th,Chemistry,5.3,86.20,70.4,100.0,94.5,95.6
73,STU050,Student 050,Male,11th,Chemistry,5.3,86.20,70.4,100.0,94.5,95.6
115,STU002,STUDENT 002,Female,10th,Computer science,5.0,83.95,100.0,100.0,86.6,95.2
133,STU002,Student 002,Female,10th,Computer science,5.0,83.95,100.0,100.0,86.6,95.2
147,STU040,Student 040,Female,9th,Mathematics,6.0,88.00,96.0,100.0,85.9,94.5
98,STU140,Student 140,Male,10th,Mathematics,5.2,81.40,80.7,100.0,100.0,93.9
103,STU061,Student 061,Male,11th,Chemistry,4.9,88.00,79.5,87.2,100.0,93.9
30,STU101,Student 101,Female,10th,Mathematics,4.9,88.20,88.8,81.8,95.5,93.5

In [ ]:
clean_df.groupby("Subject")["Overall Score"].mean().sort_values(
    ascending=False
)

Subject
physics             96.000000
math                89.050000
Computer science    81.500000
English             76.340741
Computer Science    75.052381
Physics             73.850000
Mathematics         73.448571
Chemistry           72.150000
 ENGLISH            71.650000
MATHEMATICS         59.900000
Name: Overall Score, dtype: float64

In [ ]:
clean_df.groupby("Class")["Overall Score"].mean().sort_values(
    ascending=False
)

Class
11 th      90.200000
12th       83.600000
 9th       79.650000
10th       78.090244
9th        74.644444
10TH       73.533333
11th       73.072727
12th       71.513889
Unknown    64.025000
Name: Overall Score, dtype: float64

In [ ]:
clean_df.dtypes

Student ID              str
Student Name            str
Gender                  str
Class                   str
Subject                 str
Study Hours         float64
Attendance %        float64
Assignment Score    float64
Midterm Score       float64
Final Exam Score    float64
Overall Score       float64
dtype: object

In [ ]:
clean_df.to_csv(
    "../data/student_performance_cleaned.csv",
    index=False
)